### PR TITLE
previous Next release

### PR DESCRIPTION
**Pull request by sigveka**
Have a look at the changes I have made to your files in US_Density. (ignore Mohsens files, they were not supposed to be included in the pull request).

Example and Detailed code are now compiled **only** using `cmake`. I believe some more "README" information would be nice for the user, I added a suggestion in `application/PUFoam/US_Density/`. Amongst other things I removed `in.txt` and `out.txt` and wrote a README for how to test the cde in README.md. I'm not sure if that is how it is usually done, but at least we do not have "random" "in/out" files lying around at least I find that a bit confusing ("are they important/not important?" etc.).

Do you think these changes could be applied to all your models?

### CODE REVIEW

**Comment by JonasMairhofer** [comment]
Hey Sigve,

thanks for the comments.
I will check that tomorrow.

Jonas
Am 28.09.2015 16:06 schrieb "Sigve Karolius" notifications@github.com:

**Comment by sigveka** [comment]
No problem,

I have actually made the edits in US_Solubility_Model as well, but
SurfaceTension will require some more “engineering”.

I am trying to do make DFT, but I am getting the error:

```
          call SNESSetJacobian(snes,J,J,SNESComputeJacobianDefault,PETSC_NU



                                                                  1
```

Error: Symbol 'snescomputejacobiandefault' at (1) has no IMPLICIT type

make: **\* [SolverSetup.o] Error 1

I have installed PETSC following the instructions here
http://modb.oce.ulg.ac.be/mediawiki/index.php/PETSC#Installation_of_PETSC

Any ideas?

Sigve
​

**Comment by JonasMairhofer** [comment]
Hi Sigve,

first of all thanks for merging the compilation of the detailed code and
the macroscopic code into one cmake command.
Regarding the input and output files, I left them in the folders with the
source code of the detailed models, so users who would like to run the
detailed models separately before using it in a MoDeNa style workflow
(where these files are generated automatically), have all the filed needed
to run the code.

The error you get trying to compile the Surface Tension model is probably
related to the version of PETSc you installed. If I saw correctly in the
link you added with the installation instructions, you installed PETSc
3.3.  I used PETSc 3.4 when I wrote the code. Different versions of PETSc
are usually not 100% compatible, therefore, also installing something newer
than 3.4 will lead to compilation errors.

Regards,
Jonas

**Comment by henrus** [comment]
I agree with Jonas. It should be possible to compile each code individually. However, there could be a global cmake.txt that triggers compilation of the sub-projects - There is a cmake command for this (not include directory).

**Comment by sigveka** [comment]
Not sure if I understand exactly what you mean Henrik, but I shall conform
to the majority opinion.

Not sure why I am apprehensive about a directory of source code containing
“alien” files. That being said, I am well known for being oppressive
against files that can be auto-generated or whose purpose is not clear rm
-rf *.rubbish :p

When we change back to the previous strategy I will propose one change; to
edit the path in BackwardMappingScriptTask, i.e. the to the executable
detailed code. The reason is that I do _not_ want to ask a user to do “copy
and paste” of executables.

As a user I want to open a README and see:
1. What software do I need.
   - This can of course be divided into “within the MoDeNa framework”
     and “as a standalone program”
2. How to compile.
3. How to get numbers.

## Ideally in three lines…

Summary:
- Go back to previous configuration
- Edit path in BackwardMappingScriptTask to point directly to the
  executable created by makefile

## Sounds good?

Regards,

Sigve
​

**Comment by henrus** [comment]
Hi Sigve,

I totally agree with you on cleaning up the code and move as much of the make systems to cmake. In my opinion there is no need to go back! All I am proposing is that we allow the user to compile their bits separately.

As for the paths in the BackwardMappingScriptTask, I think these should be relative to the location of the python module, but I am not 100% sure. Some codes, may have special requirements, in which case we could allow them to override the default.

Henrik

**Comment by sigveka** [comment]
Then I think we are all in agreement.

Relative path is a problem for modularisation. Fireworks executes the
program in a directory launcher_x,y,x, this means that when you ask the
system for PWD it will give you the path to _that_ directory. However, it
is perfectly possible that you imported the module from somewhere else.

I am circumventing this by telling the BackwardMappingScriptTask to execute
os.path.dirname(os.path.absname(**file**)), which will give the path to the
.pyc file irrespective of where the program is actually being executed. I
am expecting problems with distributed computing.

Sigve
​

**Pull request closed without merging**
